### ISSUE TITLE
Error while choosing direction

### ISSUE THREAD

**Issue by JakubBialoskorski** [Kitty667/Python---Game#1]
While pressing "Q" it shows:

```
Traceback (most recent call last):
  File "Game - excercise.py", line 44, in <module>
    direction = input("Available exits are " + availableExits).upper()
  File "<string>", line 1, in <module>
NameError: name 'Q' is not defined
```

Also, it would be nice to have a space after the "choose direction" dialog, so symbols are separated.

**Comment by fbialoskorski** [comment]
Thanks for the input. It will be included on version 1.1 with other cosmetic changes.
